//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPropertyInfoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_TBL
    {
        public long Id { get; set; }
        public string irreg_desc { get; set; }
        public string wat_desc { get; set; }
        public string ratio1 { get; set; }
        public string ratio2 { get; set; }
        public string ratio3 { get; set; }
        public string new_dist { get; set; }
        public string section { get; set; }
        public string block { get; set; }
        public string lot { get; set; }
        public string lot1 { get; set; }
        public string ht_enc { get; set; }
        public string garage { get; set; }
        public string foundation { get; set; }
        public string bsmt_fin { get; set; }
        public string basement { get; set; }
        public string irregular { get; set; }
        public string lot_acres { get; set; }
        public string rooms_bath { get; set; }
        public string waterfront { get; set; }
        public string built { get; set; }
        public string full_baths { get; set; }
        public string half_baths { get; set; }
        public string attic { get; set; }
        public string fireplace { get; set; }
        public string heat_type { get; set; }
        public string fuel_type { get; set; }
        public string ext_wall { get; set; }
        public string lot_group { get; set; }
        public string district { get; set; }
        public string dista { get; set; }
        public string township { get; set; }
        public string house_numb { get; set; }
        public string st_name { get; set; }
        public string village { get; set; }
        public string dir { get; set; }
        public string zip_code { get; set; }
        public string apt { get; set; }
        public string unit { get; set; }
        public string res_number { get; set; }
        public string res_street { get; set; }
        public string st_swis_co { get; set; }
        public string owner_name { get; set; }
        public string old_name { get; set; }
        public string mailing_ad { get; set; }
        public string mailing_a1 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code1 { get; set; }
        public string prop_class { get; set; }
        public string class_suf { get; set; }
        public string tax_class { get; set; }
        public string lot_size { get; set; }
        public string cav_land { get; set; }
        public string cav_total { get; set; }
        public string av_land { get; set; }
        public string av_total { get; set; }
        public string town_code { get; set; }
        public string lsqft { get; set; }
        public string str_ind { get; set; }
        public string bc_amt { get; set; }
        public string ed_amt { get; set; }
        public string style { get; set; }
        public string livunit { get; set; }
        public string rec_no { get; set; }
        public string condolvl { get; set; }
        public string lspace { get; set; }
        public string east { get; set; }
        public string north { get; set; }
        public string street { get; set; }
        public string traffic { get; set; }
        public string topo { get; set; }
        public string loc { get; set; }
        public string fron { get; set; }
        public string util { get; set; }
        public string code { get; set; }
        public string mgfa { get; set; }
        public string src { get; set; }
        public string tsplit { get; set; }
        public string highlight { get; set; }
        public string fld_pnl { get; set; }
        public string fld_zn { get; set; }
        public string fld_dt { get; set; }
        public string rate_t { get; set; }
        public string recno { get; set; }
        public string Client1 { get; set; }
        public string Client2 { get; set; }
        public string Client3 { get; set; }
        public string Client4 { get; set; }
        public string Client5 { get; set; }
        public string Client6 { get; set; }
        public string Client7 { get; set; }
        public string Client8 { get; set; }
        public string Client9 { get; set; }
        public string Client10 { get; set; }
        public string Client11 { get; set; }
        public string Client12 { get; set; }
        public string Client13 { get; set; }
        public string Client14 { get; set; }
        public string Client15 { get; set; }
        public string SalesPrice { get; set; }
        public string SalesDate { get; set; }
        public string Town { get; set; }
    }
}
